[project]
name = "library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-browser-reload>=1.20.0",
    "django-environ>=0.12.0",
    "django-tailwind-cli>=4.4.0",
    "psycopg>=3.2.10",
]
