# Generated by Django 5.2.6 on 2025-09-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned'), ('can_renew', 'Set book as renewed')]},
        ),
    ]
