# Generated by Django 5.2.6 on 2025-09-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add_author', 'Add new author'), ('can_change_author', 'Change author info'), ('can_delete_author', 'Delete existing author')]},
        ),
    ]
